[project]
name = "prosper-server"
version = "0.1.0"
description = "Twilio webhook server for Prosper agent"
requires-python = ">=3.10"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "python-dotenv",
  "twilio",
  "python-multipart",
]
